# Generated by Django 5.2.2 on 2025-06-09 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_testimonial_photo_testimonial_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='animal_name',
            field=models.CharField(default='Unknown', max_length=100),
            preserve_default=False,
        ),
    ]
