# Generated by Django 5.2.2 on 2025-06-11 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_volunteer_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdoptionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('reason', models.TextField()),
                ('animal_name', models.CharField(max_length=100)),
                ('animal_age', models.CharField(max_length=50)),
                ('animal_gender', models.CharField(max_length=10)),
                ('animal_breed', models.CharField(max_length=100)),
                ('animal_personality', models.TextField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
