# Generated by Django 5.2.2 on 2025-07-13 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_adoptionrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testimonial',
            name='photo',
        ),
        migrations.AddField(
            model_name='testimonial',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
