# Generated by Django 5.2.2 on 2025-07-19 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_testimonial_photo_testimonial_image_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomepageStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animals_rescued', models.CharField(default='10,000+', max_length=50)),
                ('sterilizations_done', models.CharField(default='30,000+', max_length=50)),
            ],
        ),
    ]
