# Generated by Django 5.2.2 on 2025-07-19 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_corevalue'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abc_surgeries_count', models.CharField(default='30,000+', max_length=50)),
            ],
        ),
    ]
