# Generated by Django 5.2.2 on 2025-07-19 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_aboutstats'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ambulance_phone', models.CharField(default='+91 9212797696', max_length=20)),
            ],
        ),
    ]
