# Generated by Django 5.2.2 on 2025-07-20 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_activityinfo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homepagestats',
            options={'verbose_name': 'Homepage Stats', 'verbose_name_plural': 'Homepage Stats'},
        ),
        migrations.AddField(
            model_name='testimonial',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='testimonials/'),
        ),
    ]
