# Generated by Django 5.2.2 on 2025-07-20 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_homepagestats_options_testimonial_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testimonial',
            name='image',
        ),
    ]
